# Generated by Django 4.2.1 on 2023-05-28 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_ong', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ongs',
            new_name='participantes',
        ),
    ]
