# Generated by Django 4.2.1 on 2023-05-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateTimeField(verbose_name='data de nascimento')),
                ('porte', models.CharField(max_length=10)),
                ('sexo', models.CharField(max_length=5)),
                ('cor', models.CharField(max_length=200)),
                ('localizacao', models.CharField(max_length=500)),
                ('comportamento', models.CharField(max_length=500)),
                ('foto', models.FileField(upload_to='')),
            ],
        ),
    ]
