# Generated by Django 4.2.1 on 2023-05-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petmatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='email_contato',
            field=models.CharField(default='noreply@noreply.com.br', max_length=500),
        ),
    ]
