# Generated by Django 4.2.1 on 2023-05-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petmatch', '0003_alter_pet_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ONG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf_cnpj', models.CharField(max_length=14)),
                ('telefone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=8)),
                ('rua', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='pet',
            name='foto',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
