# Generated by Django 4.2.1 on 2023-11-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petmatch', '0004_ong_alter_pet_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='latitude',
            field=models.IntegerField(default=-46.6349803, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='pet',
            name='longitude',
            field=models.IntegerField(default=-23.5514953, verbose_name='Longitude'),
        ),
    ]
