# Generated by Django 4.2.1 on 2023-11-05 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petmatch', '0006_alter_pet_latitude_alter_pet_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='longitude',
        ),
    ]
